import { MapGameMode, type Map } from "./types";

export const Maps: Map[] = [
  { name: "Hanaoka", gameMode: MapGameMode.Clash },
  { name: "Throne of Anubis", gameMode: MapGameMode.Clash },
  { name: "Antarctic Peninsula", gameMode: MapGameMode.Control },
  { name: "Busan", gameMode: MapGameMode.Control },
  { name: "Ilios", gameMode: MapGameMode.Control },
  { name: "Lijang Tower", gameMode: MapGameMode.Control },
  { name: "Nepal", gameMode: MapGameMode.Control },
  { name: "Oasis", gameMode: MapGameMode.Control },
  { name: "Samoa", gameMode: MapGameMode.Control },
  { name: "Circuit Royal", gameMode: MapGameMode.Escort },
  { name: "Dorado", gameMode: MapGameMode.Escort },
  { name: "Havana", gameMode: MapGameMode.Escort },
  { name: "Junkertown", gameMode: MapGameMode.Escort },
  { name: "Rialto", gameMode: MapGameMode.Escort },
  { name: "Route 66", gameMode: MapGameMode.Escort },
  { name: "Shambali Monastery", gameMode: MapGameMode.Escort },
  { name: "Watchpoint: Gibraltar", gameMode: MapGameMode.Escort },
  { name: "Aatlis", gameMode: MapGameMode.Flashpoint },
  { name: "New Junk City", gameMode: MapGameMode.Flashpoint },
  { name: "Suravasa", gameMode: MapGameMode.Flashpoint },
  { name: "Blizzard World", gameMode: MapGameMode.Hybrid },
  { name: "Eichenwalde", gameMode: MapGameMode.Hybrid },
  { name: "Hollywood", gameMode: MapGameMode.Hybrid },
  { name: "King's Row", gameMode: MapGameMode.Hybrid },
  { name: "Midtown", gameMode: MapGameMode.Hybrid },
  { name: "Numbani", gameMode: MapGameMode.Hybrid },
  { name: "Paraíso", gameMode: MapGameMode.Hybrid },
  { name: "Colosseo", gameMode: MapGameMode.Push },
  { name: "Esperança", gameMode: MapGameMode.Push },
  { name: "New Queen Street", gameMode: MapGameMode.Push },
  { name: "Runasapi", gameMode: MapGameMode.Push },
]
